@startuml classdiagram


class Model {
    -name : String
    -values : Map<String, Integer>
    -view : View
    +Model(name : String)
    +getName() : String
    +setName(name : String) : void
    +getValues() Map<String, Integer>
    +setValues(values : Map<String, Integer>) : void
    +setValue(key : String, value : int) : Integer
    +getValue(key : String) : int
    +getView() : view
    +setView(view : View) : void
    +handleIntent(intent : Intent) : void
    +updateSpinnerState (targetName : String, value : int) : void
}

interface Intent {
}


class UpdateValueIntent implements Intent {
    -sourceName : String
    -targetName : String
    -value : int
    +UpdateValueIntent(sourceName : String, targetName : String, value : int)
    +getSourceName() : String
    +setSourceName(sourceName : String) : void
    +getTargetName() : String
    +setTargetName(targetName String) : void
    +getValue() : int
    +setValue(value : int) : void
    
}
class View {
    -model : Model
    -contentPane : JPanel
    -spinner001 : JSpinner
    -spinner002 : JSpinner
    -spinner003 : JSpinner
    -spinner001b : JSpinner
    -spinner002b : JSpinner
    -spinner003b : JSpinner
    -modelName : String
    +View(model : Model)
    +updateViewState(targetName : String, value : Object) : void
    +getModelName() : String
    +setModelName(modelName : String) : void
    +setModel(model : Model) : void
}

Class MVIApp {
    +main(args : String[]) : void
}

MVIApp --> Model
MVIApp --> View
MVIApp --> Intent
View --> Model
Model --> View


@enduml
